runtime: nodejs20

env_variables:
  NODE_ENV: production
  # Kolkata (Asia/Kolkata) UTC+05:30
  TIMEZONE_OFFSET_MINUTES: 330
  TZ: Asia/Kolkata

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: auto